databaseChangeLog:
  - changeSet:
      id: 010-01
      author: cascade
      changes:
        - createTable:
            tableName: user_settings
            columns:
              - column: {name: id, type: UUID, constraints: {primaryKey: true}}
              - column: {name: user_id, type: UUID, constraints: {nullable: false, unique: true}}
              - column: {name: settings, type: jsonb, constraints: {nullable: false}}
              - column: {name: created_at, type: timestamp, defaultValueComputed: CURRENT_TIMESTAMP}
              - column: {name: updated_at, type: timestamp}
        - addForeignKeyConstraint:
            constraintName: fk_user_settings_user
            baseTableName: user_settings
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            onDelete: CASCADE
