databaseChangeLog:
  - changeSet:
      id: 015-01
      author: cascade
      changes:
        - createTable:
            tableName: system_settings
            columns:
              - column: {name: id, type: UUID, constraints: {primaryKey: true}}
              - column: {name: setting_key, type: VARCHAR(100), constraints: {nullable: false}}
              - column: {name: value, type: TEXT, constraints: {nullable: false}}
              - column: {name: created_at, type: TIMESTAMP WITH TIME ZONE, defaultValueComputed: CURRENT_TIMESTAMP}
              - column: {name: updated_at, type: TIMESTAMP WITH TIME ZONE, defaultValueComputed: CURRENT_TIMESTAMP}
        - addUniqueConstraint:
            tableName: system_settings
            columnNames: setting_key
            constraintName: uq_system_setting_key
