databaseChangeLog:
  - changeSet:
      id: 005-01
      author: cascade
      changes:
        - createTable:
            tableName: organization_settings
            columns:
              - column: {name: id, type: UUID, constraints: {primaryKey: true}}
              - column: {name: organization_id, type: UUID, constraints: {nullable: false, unique: true}}
              - column: {name: settings, type: jsonb, constraints: {nullable: false}}
              - column: {name: created_at, type: timestamp, defaultValueComputed: CURRENT_TIMESTAMP}
              - column: {name: updated_at, type: timestamp}
        - createIndex:
            tableName: organization_settings
            indexName: idx_settings_org
            columns:
              - column: {name: organization_id}
